---
title: "DM-eksamen-kode"
author: "Andreas LN"
date: '2022-06-23'
output: pdf_document
---


# K MEANS CALCULATION:
```{r}
one_dim <- function(x,y)
	abs(x-y)^2

two_dim <- function(x,y,z,d)
	(abs(x-y)^2)+(abs(z-d)^2)
```

```{r}

# CALCULATE TD2 OF S(1)
x1 <- one_dim(3,1) # 3 and 1
x2 <- one_dim(3,3) # 3 with itself
x3 <- one_dim(3,5) # 3 and 5

x4 <- one_dim(10,7) # 10 and 7
x5 <- one_dim(10,10) # 10 and 10
x6 <- one_dim(10,11) # 10 and 11
x7 <- one_dim (10,12) # 10 and 12
```

```{r}
s1 <- sum(x1,x2,x3,x4,x5,x6,x7)
s1
```



```{r}
# CALCULATE TD2 FOR S(2)
mean_s21 <- (1+3)/2
mean_s21
mean_s22 <- (5+7)/2
mean_s22
mean_s23 <- (10+11+12)/3
mean_s23

x11 <- one_dim(2,1) # 2 and 1
x21 <- one_dim(2,3) # 2 and 3

x31 <- one_dim(6,5) # 6 and 5
x41 <- one_dim(6,7) # 6 and 7

x51 <- one_dim(11,10) # 11 and 10
x61 <- one_dim(11,11) # 11 and 11
x71 <- one_dim (11,12) # 11 and 12
```
```{r}
s2 <- sum(x11,x21,x31,x41,x51,x61,x71)
s2
```

```{r}
# CALCULATE TD2 FOR S(2)
mean_s31 <- (1+3+5+7)/4
mean_s31
mean_s32 <- (10+11+12)/3
mean_s32


x12 <- one_dim(4,1) # 4 and 1
x22 <- one_dim(4,3) # 4 and 3
x32 <- one_dim(4,5) # 4 and 5
x42 <- one_dim(4,7) # 4 and 7

x52 <- one_dim(11,10) # 11 and 10
x62 <- one_dim(11,11) # 11 and 11
x72 <- one_dim (11,12) # 11 and 12
```
```{r}
s3 <- sum(x12,x22,x32,x42,x52,x62,x72)
s3
```

\newpage

# Silhoutte score

```{r}
# S1

a1 <- one_dim(3,1)
b1 <- one_dim(10,1)
a2 <- one_dim(3,3)
b2 <- one_dim(10,3)
a3 <- one_dim(3,5)
b3 <- one_dim(10,5)

a4 <- one_dim(10,7)
b4 <- one_dim(3,7)
a5 <- one_dim(10,10)
b5 <- one_dim(3,10)
a6 <- one_dim(10,11)
b6 <- one_dim(3,11)
a7 <- one_dim(10,12)
b7 <- one_dim(3,12)
```

# SILHOUETTE SCORE:

```{r}
sil <- function(a,b)
  (b-a)/max(a,b)

```

```{r}

# Calc sil. score for s1
sil11 <- sil(a1,b1)
sil21 <- sil(a2,b2)
sil31 <- sil(a3,b3)
sil41 <- sil(a4,b4)
sil51 <- sil(a5,b5)
sil61 <- sil(a6,b6)
sil71 <- sil(a7,b7)


# Finding sil score for s1:
(sil11+sil21+sil31+sil41+sil51+sil61+sil71)/7

```



```{r}
# S2

#Cluster1
a12 <- one_dim(2,1)
b12 <- one_dim(6,1)
c12 <- one_dim(11,1)

a22 <- one_dim(2,3)
b22 <- one_dim(6,3)
c22 <- one_dim(11,3)


#Cluster2
a32 <- one_dim(2,5)
b32 <- one_dim(6,5)
c32 <- one_dim(11,5)

a42 <- one_dim(2,7)
b42 <- one_dim(6,7)
c42 <- one_dim(11,7)

#Cluster3
a52 <- one_dim(2,10)
b52 <- one_dim(6,10)
c52 <- one_dim(11,10)

a62 <- one_dim(2,11)
b62 <- one_dim(6,11)
c62 <- one_dim(11,11)

a72 <- one_dim(2,12)
b72 <- one_dim(6,12)
c72 <- one_dim(11,12)
```


```{r}

# Calc sil. score for s2
sil12 <- sil(a1,b1)
sil22 <- sil(a2,b2)
sil32 <- sil(a3,b3)
sil42 <- sil(a4,b4)
sil52 <- sil(a5,b5)
sil62 <- sil(a6,b6)
sil72 <- sil(a7,b7)


# Finding sil score for s1:
(sil1+sil2+sil3+sil4+sil5+sil6+sil7)/7

```


